version: '3'
volumes:
  postgres_data:
    driver: local
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: genpare
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/genpare
      PORT: 8000
      HOSTNAME: 0.0.0.0
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      VITE_BASE_URL: http://localhost:8000
    depends_on:
      - server
    ports:
      - '80:3000'
